# Generated by Django 3.2.4 on 2021-06-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_reaction_post_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
